// Mapping des pays vers leurs continents
export const COUNTRY_TO_CONTINENT: { [country: string]: string } = {
  // Afrique
  'Algeria': 'Afrique',
  'Angola': 'Afrique',
  'Benin': 'Afrique',
  'Botswana': 'Afrique',
  'Burkina Faso': 'Afrique',
  'Burundi': 'Afrique',
  'Cabo Verde': 'Afrique',
  'Cameroon': 'Afrique',
  'Central African Republic': 'Afrique',
  'Chad': 'Afrique',
  'Comoros': 'Afrique',
  'Congo (Brazzaville)': 'Afrique',
  'Congo (Kinshasa)': 'Afrique',
  "Cote d'Ivoire": 'Afrique',
  'Djibouti': 'Afrique',
  'Egypt': 'Afrique',
  'Equatorial Guinea': 'Afrique',
  'Eritrea': 'Afrique',
  'Eswatini': 'Afrique',
  'Ethiopia': 'Afrique',
  'Gabon': 'Afrique',
  'Gambia': 'Afrique',
  'Ghana': 'Afrique',
  'Guinea': 'Afrique',
  'Guinea-Bissau': 'Afrique',
  'Kenya': 'Afrique',
  'Lesotho': 'Afrique',
  'Liberia': 'Afrique',
  'Libya': 'Afrique',
  'Madagascar': 'Afrique',
  'Malawi': 'Afrique',
  'Mali': 'Afrique',
  'Mauritania': 'Afrique',
  'Mauritius': 'Afrique',
  'Morocco': 'Afrique',
  'Mozambique': 'Afrique',
  'Namibia': 'Afrique',
  'Niger': 'Afrique',
  'Nigeria': 'Afrique',
  'Rwanda': 'Afrique',
  'Sao Tome and Principe': 'Afrique',
  'Senegal': 'Afrique',
  'Seychelles': 'Afrique',
  'Sierra Leone': 'Afrique',
  'Somalia': 'Afrique',
  'South Africa': 'Afrique',
  'South Sudan': 'Afrique',
  'Sudan': 'Afrique',
  'Tanzania': 'Afrique',
  'Togo': 'Afrique',
  'Tunisia': 'Afrique',
  'Uganda': 'Afrique',
  'Zambia': 'Afrique',
  'Zimbabwe': 'Afrique',

  // Asie
  'Afghanistan': 'Asie',
  'Armenia': 'Asie',
  'Azerbaijan': 'Asie',
  'Bahrain': 'Asie',
  'Bangladesh': 'Asie',
  'Bhutan': 'Asie',
  'Brunei': 'Asie',
  'Burma': 'Asie',
  'Cambodia': 'Asie',
  'China': 'Asie',
  'Cyprus': 'Asie',
  'Georgia': 'Asie',
  'India': 'Asie',
  'Indonesia': 'Asie',
  'Iran': 'Asie',
  'Iraq': 'Asie',
  'Israel': 'Asie',
  'Japan': 'Asie',
  'Jordan': 'Asie',
  'Kazakhstan': 'Asie',
  'Korea, South': 'Asie',
  'Kuwait': 'Asie',
  'Kyrgyzstan': 'Asie',
  'Laos': 'Asie',
  'Lebanon': 'Asie',
  'Malaysia': 'Asie',
  'Maldives': 'Asie',
  'Mongolia': 'Asie',
  'Nepal': 'Asie',
  'Oman': 'Asie',
  'Pakistan': 'Asie',
  'Philippines': 'Asie',
  'Qatar': 'Asie',
  'Saudi Arabia': 'Asie',
  'Singapore': 'Asie',
  'Sri Lanka': 'Asie',
  'Syria': 'Asie',
  'Taiwan*': 'Asie',
  'Tajikistan': 'Asie',
  'Thailand': 'Asie',
  'Timor-Leste': 'Asie',
  'Turkey': 'Asie',
  'Turkmenistan': 'Asie',
  'United Arab Emirates': 'Asie',
  'Uzbekistan': 'Asie',
  'Vietnam': 'Asie',
  'Yemen': 'Asie',

  // Europe
  'Albania': 'Europe',
  'Andorra': 'Europe',
  'Austria': 'Europe',
  'Belarus': 'Europe',
  'Belgium': 'Europe',
  'Bosnia and Herzegovina': 'Europe',
  'Bulgaria': 'Europe',
  'Croatia': 'Europe',
  'Czechia': 'Europe',
  'Denmark': 'Europe',
  'Estonia': 'Europe',
  'Finland': 'Europe',
  'France': 'Europe',
  'Germany': 'Europe',
  'Greece': 'Europe',
  'Holy See': 'Europe',
  'Hungary': 'Europe',
  'Iceland': 'Europe',
  'Ireland': 'Europe',
  'Italy': 'Europe',
  'Kosovo': 'Europe',
  'Latvia': 'Europe',
  'Liechtenstein': 'Europe',
  'Lithuania': 'Europe',
  'Luxembourg': 'Europe',
  'Malta': 'Europe',
  'Moldova': 'Europe',
  'Monaco': 'Europe',
  'Montenegro': 'Europe',
  'Netherlands': 'Europe',
  'North Macedonia': 'Europe',
  'Norway': 'Europe',
  'Poland': 'Europe',
  'Portugal': 'Europe',
  'Romania': 'Europe',
  'Russia': 'Europe',
  'San Marino': 'Europe',
  'Serbia': 'Europe',
  'Slovakia': 'Europe',
  'Slovenia': 'Europe',
  'Spain': 'Europe',
  'Sweden': 'Europe',
  'Switzerland': 'Europe',
  'Ukraine': 'Europe',
  'United Kingdom': 'Europe',

  // Amérique du Nord
  'Antigua and Barbuda': 'Amérique du Nord',
  'Bahamas': 'Amérique du Nord',
  'Barbados': 'Amérique du Nord',
  'Belize': 'Amérique du Nord',
  'Canada': 'Amérique du Nord',
  'Costa Rica': 'Amérique du Nord',
  'Cuba': 'Amérique du Nord',
  'Dominica': 'Amérique du Nord',
  'Dominican Republic': 'Amérique du Nord',
  'El Salvador': 'Amérique du Nord',
  'Grenada': 'Amérique du Nord',
  'Guatemala': 'Amérique du Nord',
  'Haiti': 'Amérique du Nord',
  'Honduras': 'Amérique du Nord',
  'Jamaica': 'Amérique du Nord',
  'Mexico': 'Amérique du Nord',
  'Nicaragua': 'Amérique du Nord',
  'Panama': 'Amérique du Nord',
  'Saint Kitts and Nevis': 'Amérique du Nord',
  'Saint Lucia': 'Amérique du Nord',
  'Saint Vincent and the Grenadines': 'Amérique du Nord',
  'Trinidad and Tobago': 'Amérique du Nord',
  'US': 'Amérique du Nord',

  // Amérique du Sud
  'Argentina': 'Amérique du Sud',
  'Bolivia': 'Amérique du Sud',
  'Brazil': 'Amérique du Sud',
  'Chile': 'Amérique du Sud',
  'Colombia': 'Amérique du Sud',
  'Ecuador': 'Amérique du Sud',
  'Guyana': 'Amérique du Sud',
  'Paraguay': 'Amérique du Sud',
  'Peru': 'Amérique du Sud',
  'Suriname': 'Amérique du Sud',
  'Uruguay': 'Amérique du Sud',
  'Venezuela': 'Amérique du Sud',

  // Océanie
  'Australia': 'Océanie',
  'Fiji': 'Océanie',
  'Kiribati': 'Océanie',
  'Marshall Islands': 'Océanie',
  'Micronesia': 'Océanie',
  'Nauru': 'Océanie',
  'New Zealand': 'Océanie',
  'Palau': 'Océanie',
  'Papua New Guinea': 'Océanie',
  'Samoa': 'Océanie',
  'Solomon Islands': 'Océanie',
  'Tonga': 'Océanie',
  'Tuvalu': 'Océanie',
  'Vanuatu': 'Océanie',
};

export const CONTINENTS = [
  'Afrique',
  'Asie',
  'Europe',
  'Amérique du Nord',
  'Amérique du Sud',
  'Océanie'
];

export function getContinent(country: string): string {
  return COUNTRY_TO_CONTINENT[country] || 'Autre';
}

export function getCountriesByContinent(continent: string, countries: string[]): string[] {
  return countries.filter(country => getContinent(country) === continent);
}

export const CONTINENT_COLORS: { [continent: string]: string } = {
  'Afrique': '#f59e0b',
  'Asie': '#ef4444',
  'Europe': '#3b82f6',
  'Amérique du Nord': '#10b981',
  'Amérique du Sud': '#8b5cf6',
  'Océanie': '#14b8a6',
  'Autre': '#6b7280'
};
